---
autonetsec:
  children:

    router:
      hosts:
        edge-router:

        server-router:
     
        dmz-router:
       

    switches:
      children:
        l2-switch:
          hosts:
            fin-sw:
             
            hr-sw:
             
            dmz-sw:
             
            server-sw:
              

        l3-switch:
          children:
            core-sw:
              hosts:
                core-switch:
                  
            dist-sw:
              hosts:
                dist-sw1:
                
                dist-sw2:
                  

    firewall:
      children:
        security-gateway:
          hosts:
            cpsg-fw1:
          
        management-server:
          hosts:
            cpsms:
              

    dmz:
      children:
        web:
          hosts:
            nginx-webserver:
              
        dns:
          hosts:
            dns-server:
             
        mail:
          hosts:
            mail-server:
              

    
