- name: Install and configure DNS
  become: true
  ansible.builtin.apt:
    name: bind9
    state: present
- name: Ensure DNS service is enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
