---

- name: Run all configurations
  host: all
  gather_facts: no
  roles:
    - common

- import_playbook: configure_router.yaml
- import_playbook: configure_firewall.yaml
- import_playbook: configure_switches.yaml
- import_playbook: configure_servers.yaml
